# Generated by Django 5.2.7 on 2025-11-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_person_cartitem_name_alter_cart_user'),
        ('resume', '0003_alter_resume_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resume.resume'),
        ),
    ]
