# Generated by Django 5.2.7 on 2025-10-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.category'),
        ),
    ]
