# Generated by Django 5.2.7 on 2025-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='father_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
